### ISSUE TITLE
xsd loading problems

### ISSUE THREAD

**Issue by debuti** [modelica/DCPTestGenerator#2]
After successfully building the tool you end up having the following issue
```
bgarciagonzalez@28APO3997:~/DCPTestGenerator/target$ ./XmlTemplateParser.exe 
run-detectors: unable to find an interpreter for ./XmlTemplateParser.exe
```

If you try the shaded jar the getClassLoader is not able to access its own resources
```
bgarciagonzalez@28APO3997:~/DCPTestGenerator$ java -jar target/PathExpander-0.0.1-SNAPSHOT-shaded.jar -dcpx pid.dcpx -UDP
org.xml.sax.SAXParseException; schema_reference.4: Failed to read schema document 'file:/home/bgarciagonzalez/DCPTestGenerator/file:/home/bgarciagonzalez/DCPTestGenerator/target/PathExpander-0.0.1-SNAPSHOT-shaded.jar!/xsd/dcpSlaveDescription.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
```

you can tweak that paths to point outside the jar but you wont get far
```
bgarciagonzalez@28APO3997:~/DCPTestGenerator$ java -jar target/PathExpander-0.0.1-SNAPSHOT-shaded.jar -dcpx pid.dcpx -UDP
Error while loading dcpx: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
```

The system I'm running on is 
> Ubuntu 18.04.2 LTS \n \l
> Linux 28APO3997 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ChKater** [comment]
What Java Version do you use? We used Java 8 for development. Java 10 brings some changes in default packages of the JDK. The tool probably need some adjustment to work with Java 10.

**Comment by debuti** [comment]
I tried both with Java 8 and Java 11 (the first message outputs) with same results, see
```
bgarciagonzalez@28APO3997:~/DCPTestGenerator$ JAVA_HOME=/usr/lib/jvm/java-8-oracle mvn --version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-47-generic", arch: "amd64", family: "unix"

bgarciagonzalez@28APO3997:~/DCPTestGenerator$ JAVA_HOME=/usr/lib/jvm/java-8-oracle mvn clean package
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for luh.sim:PathExpander:jar:0.0.1-SNAPSHOT
[WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead.
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------------< luh.sim:PathExpander >------------------------
[INFO] Building PathExpander 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ PathExpander ---
[INFO] Deleting /home/bgarciagonzalez/DCPTestGenerator/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ PathExpander ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 25 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ PathExpander ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 58 source files to /home/bgarciagonzalez/DCPTestGenerator/target/classes
[INFO] /home/bgarciagonzalez/DCPTestGenerator/src/main/java/main/Launcher.java: /home/bgarciagonzalez/DCPTestGenerator/src/main/java/main/Launcher.java uses or overrides a deprecated API.
[INFO] /home/bgarciagonzalez/DCPTestGenerator/src/main/java/main/Launcher.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ PathExpander ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/bgarciagonzalez/DCPTestGenerator/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ PathExpander ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ PathExpander ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ PathExpander ---
[INFO] Building jar: /home/bgarciagonzalez/DCPTestGenerator/target/PathExpander-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-shade-plugin:1.7.1:shade (default) @ PathExpander ---
[INFO] Including javax.xml.bind:jaxb-api:jar:2.3.0 in the shaded jar.
[INFO] Including org.graphstream:gs-core:jar:1.3 in the shaded jar.
[INFO] Including org.graphstream:pherd:jar:1.0 in the shaded jar.
[INFO] Including org.graphstream:mbox2:jar:1.0 in the shaded jar.
[INFO] Including com.google.code.gson:gson:jar:2.8.2 in the shaded jar.
[INFO] Including commons-cli:commons-cli:jar:1.3.1 in the shaded jar.
[INFO] Attaching shaded artifact.
[INFO] 
[INFO] --- launch4j-maven-plugin:1.5.1:launch4j (l4j-clui) @ PathExpander ---
[INFO] Platform-specific work directory already exists: /home/bgarciagonzalez/.m2/repository/com/akathist/maven/plugins/launch4j/launch4j-maven-plugin/1.5.1
[INFO] launch4j: Compiling resources
[INFO] launch4j: Linking
[INFO] launch4j: Wrapping
[INFO] launch4j: Successfully created /home/bgarciagonzalez/DCPTestGenerator/target/XmlTemplateParser.exe
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.618 s
[INFO] Finished at: 2019-05-14T13:52:45+02:00
[INFO] ------------------------------------------------------------------------

bgarciagonzalez@28APO3997:~/DCPTestGenerator$ ./target/XmlTemplateParser.exe 
run-detectors: unable to find an interpreter for ./target/XmlTemplateParser.exe

bgarciagonzalez@28APO3997:~/DCPTestGenerator$ /usr/lib/jvm/java-8-oracle/bin/java -jar target/PathExpander-0.0.1-SNAPSHOT-shaded.jar -dcpx pid.dcpx -UDP
org.xml.sax.SAXParseException; schema_reference.4: Failed to read schema document 'file:/home/bgarciagonzalez/DCPTestGenerator/file:/home/bgarciagonzalez/DCPTestGenerator/target/PathExpander-0.0.1-SNAPSHOT-shaded.jar!/xsd/dcpSlaveDescription.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:306)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4158)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:4141)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument1(XSDHandler.java:2480)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2193)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:578)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:610)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:569)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:535)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:254)
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:638)
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:654)
	at Loader.Loader.validateXMLSchema(Loader.java:115)
	at Loader.Loader.loadSlaveDescriptionFromXml(Loader.java:85)
	at main.Launcher.main(Launcher.java:130)
Caused by: java.io.FileNotFoundException: /home/bgarciagonzalez/DCPTestGenerator/file:/home/bgarciagonzalez/DCPTestGenerator/target/PathExpander-0.0.1-SNAPSHOT-shaded.jar!/xsd/dcpSlaveDescription.xsd (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:623)
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:583)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:686)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaDOMParser.parse(SchemaDOMParser.java:530)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2181)
	... 10 more
Error while loading dcpx: Slave Description XML is not valid !
```

**Comment by dev-gb** [comment]
The XmlTemplateParser.exe can't find the included resources
quick fixed it by using paths instead of resources in all files. (Loader.java, Launcher.java)

`//extension = classLoader.getResource(extensionPath + ".xml").getPath();`
`extension = extensionPath + ".xml";`

The .exe needs the resource folders in the execution path

**Comment by dev-gb** [comment]
The TemplateParser had also troubles parsing this line.

https://github.com/modelica/DCPTestGenerator/blob/81fcf29983a26a952a8fea19fcda8d7016de5000/src/main/resources/extensions/predefined_extension_SRT_UDP.xml#L4659

```
\DCPTestGenerator\target>XmlTemplateParser.exe -dcpx dcpSlaveDescription.dcpx --Tester.host 192.168.1.12 -UDP
Slave Description was loaded.
Template loaded
Extension loaded
Generating file for : DCP-Test[dcpSlaveName=dcpslave, template=predefined_template_withoutReset.xml, extension=predefined_extension_SRT_UDP.xml].xml
Error : Engine could not execute command : determineState ( step )  == 9 ||Â determineState ( step )  == 10 || determineState ( step )  == 11
javax.script.ScriptException: <eval>:1:34 Expected ; but found determineState
determineState ( step )  == 9 ||Â determineState ( step )  == 10 || determineState ( step )  == 11
                                  ^ in <eval> at line number 1 at column number 34
```

replace it with the line below, should fix the error.
`condition="determineState(step) == 9 ||determineState(step) == 10 || determineState(step) == 11">
`
